import { useState } from 'react';
import { Bot, Sparkles } from 'lucide-react';
import { api } from '../services/api';

export default function AIWriter({ form, setForm }) {
  const [task, setTask] = useState('draft'), [topic, setTopic] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  const run = async () => { setBusy(true); setMessage(''); try { const data = await api.post('/ai/assist', { task, topic, title: form.title, excerpt: form.excerpt, content: form.content, tone: 'clear and practical' }); if (task === 'excerpt') setForm({ ...form, excerpt: data.result.split('\n').find(Boolean)?.replace(/^[-*\d.)]+\s*/, '').slice(0, 500) || data.result.slice(0, 500) }); else if (task === 'ideas') setMessage(data.result); else setForm({ ...form, content: data.result }); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  return <div className="rounded-2xl border border-blue-200 bg-blue-50 p-5 dark:border-blue-900 dark:bg-[#172c3d]"><div className="flex flex-wrap items-center gap-3"><div className="flex items-center gap-2 font-semibold text-blue-700 dark:text-blue-300"><Bot size={19} /> AI writing assistant</div><select value={task} onChange={(event) => setTask(event.target.value)} className="rounded-lg border-0 bg-white px-3 py-2 text-sm dark:bg-[#1d2d23] dark:text-white"><option value="draft">Draft article</option><option value="improve">Improve article</option><option value="excerpt">Generate excerpt</option><option value="ideas">Generate ideas</option></select><button type="button" onClick={run} disabled={busy} className="flex items-center gap-2 rounded-lg bg-blue-500 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50"><Sparkles size={15} />{busy ? 'Thinking…' : 'Run AI'}</button></div><input value={topic} onChange={(event) => setTopic(event.target.value)} placeholder="Topic or instructions for the assistant" className="mt-3 w-full rounded-lg border-0 bg-white px-3 py-2 text-sm outline-none dark:bg-[#1d2d23] dark:text-white" />{message && <pre className="mt-3 max-h-48 overflow-auto whitespace-pre-wrap rounded-lg bg-white p-3 text-sm text-gray-600 dark:bg-[#1d2d23] dark:text-gray-300">{message}</pre>}<p className="mt-2 text-xs text-blue-600/70 dark:text-blue-300/70">AI suggestions are drafts—review facts and voice before publishing.</p></div>;
}
