import { useState } from 'react';
import { Bot, Send, X } from 'lucide-react';
import { api } from '../services/api';

export default function Chatbot() {
  const [open, setOpen] = useState(false), [message, setMessage] = useState(''), [busy, setBusy] = useState(false), [messages, setMessages] = useState([{ role: 'assistant', text: 'Hi! I’m Akash’s AI assistant. Ask me about his skills, projects, blog, or experience.' }]);
  const send = async (event) => { event.preventDefault(); const text = message.trim(); if (!text || busy) return; const next = [...messages, { role: 'user', text }]; setMessages(next); setMessage(''); setBusy(true); try { const result = await api.post('/ai/chat', { message: text, history: next.map((item) => ({ role: item.role, content: item.text })) }); setMessages([...next, { role: 'assistant', text: result.answer }]); } catch (error) { setMessages([...next, { role: 'assistant', text: error.message }]); } finally { setBusy(false); } };
  return <div className="fixed bottom-5 right-5 z-40"><button onClick={() => setOpen(!open)} aria-label="Open blog guide" className="grid h-14 w-14 place-items-center rounded-full bg-blue-500 text-white shadow-xl shadow-blue-500/30 transition hover:scale-105 hover:bg-blue-400">{open ? <X /> : <Bot />}</button>{open && <div className="absolute bottom-16 right-0 flex h-[470px] w-[min(360px,calc(100vw-2rem))] flex-col overflow-hidden rounded-2xl border border-[#2d4667] bg-[#142137] shadow-2xl"><div className="flex items-center gap-3 border-b border-[#2d4667] p-4 text-white"><span className="grid h-9 w-9 place-items-center rounded-xl bg-blue-500"><Bot size={18} /></span><div><b className="block text-sm">Akash AI Assistant</b><span className="text-xs text-emerald-300">Online · Blog guide</span></div></div><div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.map((item, index) => <div key={index} className={`max-w-[88%] rounded-2xl px-3 py-2 text-sm leading-6 ${item.role === 'user' ? 'ml-auto bg-blue-500 text-white' : 'bg-[#243a2b] text-gray-200'}`}>{item.text}</div>)}{busy && <div className="w-fit rounded-2xl bg-[#243a2b] px-3 py-2 text-sm text-gray-400">Thinking…</div>}</div><form onSubmit={send} className="flex gap-2 border-t border-[#2d4667] p-3"><input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Ask about this blog…" className="min-w-0 flex-1 rounded-xl bg-[#0d1728] px-3 py-2 text-sm text-white outline-none" /><button disabled={busy} className="grid h-10 w-10 place-items-center rounded-xl bg-blue-500 text-white disabled:opacity-50"><Send size={16} /></button></form></div>}</div>;
}
