import { Link } from 'react-router-dom';
import { ArrowUpRight, Clock } from 'lucide-react';

const colors = ['bg-[#e4efff]', 'bg-[#f3eafa]', 'bg-[#e5f4ed]'];
function coverFor(post) { const value = `${post.title} ${post.category?.name || ''}`.toLowerCase(); if (value.includes('apigee')) return '/covers/apigee-api-management.svg'; if (value.includes('fastapi') || value.includes('job portal') || value.includes('pdbc')) return '/covers/fastapi-pdbc-job-portal.svg'; if (value.includes('apigee') || value.includes('api')) return '/covers/rest-api-best-practices.svg'; if (value.includes('spring') || value.includes('student')) return '/covers/spring-boot-vs-mvc.svg'; if (value.includes('linux') || value.includes('log')) return '/covers/linux-commands.svg'; if (value.includes('sql') || value.includes('database')) return '/covers/oracle-sql-interview.svg'; if (value.includes('thread') || value.includes('java')) return '/covers/java-multithreading.svg'; return null; }

export default function PostCard({ post, index = 0, featured = false }) {
  const readingTime = Math.max(1, Math.ceil((post.content?.split(/\s+/).length || 250) / 200));
  return <Link to={'/post/' + post.slug} className={`group block overflow-hidden rounded-2xl border border-[#dfe6ef] bg-white shadow-sm transition duration-300 hover:-translate-y-1 hover:border-blue-200 hover:shadow-[0_20px_50px_-24px_rgba(37,99,235,.45)] dark:border-[#30445f] dark:bg-[#142137] ${featured ? 'md:col-span-2' : ''}`}>
    <div className={`${colors[index % 3]} relative ${featured ? 'h-72' : 'h-48'} overflow-hidden p-6`}>{coverFor(post) ? <img src={post.cover_image || coverFor(post)} alt="" className="absolute inset-0 h-full w-full object-cover transition duration-500 group-hover:scale-105" loading="lazy" /> : <div className="absolute inset-0 opacity-30" style={{ backgroundImage: 'radial-gradient(circle at 75% 25%,#fff 0 2%,transparent 2.5%),radial-gradient(circle at 30% 70%,#2563eb 0 1%,transparent 1.5%)', backgroundSize: '38px 38px' }} />}<div className="absolute inset-0 bg-gradient-to-t from-black/35 to-transparent" /><span className="relative rounded-full bg-white/90 px-3 py-1 text-xs font-semibold text-blue-700">{post.category?.name}</span><ArrowUpRight className="absolute bottom-5 right-5 rounded-full bg-white/90 p-2 text-blue-700 transition group-hover:rotate-45" size={36} /></div>
    <div className="p-6"><div className="mb-3 flex items-center gap-2 text-xs text-gray-500"><span>{new Date(post.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</span><span>·</span><span className="flex items-center gap-1"><Clock size={12} /> {readingTime} min read</span></div><h3 className={`serif mb-2 text-2xl leading-tight text-ink dark:text-white ${featured ? 'md:text-3xl' : ''}`}>{post.title}</h3><p className="line-clamp-2 text-sm leading-6 text-gray-500 dark:text-gray-300">{post.excerpt}</p><div className="mt-5 flex items-center gap-2 text-sm font-semibold text-blue-600"><span className="grid h-7 w-7 place-items-center rounded-full bg-blue-100 text-xs text-blue-700">{post.author?.name?.[0]}</span>{post.author?.name}</div></div>
  </Link>;
}
