import { useEffect, useState } from 'react';
import { ArrowLeft, ImagePlus, Save } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { api } from '../services/api';
import AIWriter from '../components/AIWriter';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';
const empty = { title: '', excerpt: '', content: '', category_id: '', status: 'draft', cover_image: '' };

export default function Editor() {
  const { id } = useParams(), navigate = useNavigate();
  const [form, setForm] = useState(empty), [categories, setCategories] = useState([]), [busy, setBusy] = useState(false), [uploading, setUploading] = useState(false), [error, setError] = useState('');
  useEffect(() => { api.get('/categories').then(setCategories); if (id) api.get('/admin/posts').then((items) => { const post = items.find((item) => item.id === Number(id)); if (post) setForm({ ...post, category_id: post.category.id }); }); }, [id]);
  const change = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setError(''); try { const response = await fetch(`${API}/upload`, { method: 'POST', credentials: 'include', body: (() => { const data = new FormData(); data.append('file', file); return data; })() }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Upload failed'); setForm({ ...form, cover_image: data.url }); } catch (err) { setError(err.message); } finally { setUploading(false); } };
  const save = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { if (id) await api.put('/posts/' + id, form); else await api.post('/posts', form); navigate('/admin'); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <main className="mx-auto max-w-4xl px-5 py-12"><button onClick={() => navigate('/admin')} className="mb-8 flex items-center gap-2 text-sm font-semibold text-blue-600"><ArrowLeft size={16} /> Back to dashboard</button><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-500">{id ? 'Edit story' : 'New story'}</p><h1 className="serif mt-2 text-5xl dark:text-white">{id ? 'Refine your idea.' : 'What are you thinking about?'}</h1></div><AIWriter form={form} setForm={setForm} /><form onSubmit={save} className="space-y-5"><input required name="title" value={form.title} onChange={change} placeholder="Title" className="w-full rounded-2xl border border-[#dce5dc] bg-white p-4 text-2xl outline-none focus:border-blue-400 dark:border-[#304638] dark:bg-[#1d2d23] dark:text-white" /><input required minLength="10" name="excerpt" value={form.excerpt} onChange={change} placeholder="A short excerpt" className="w-full rounded-xl border border-[#dce5dc] bg-white p-3 outline-none focus:border-blue-400 dark:border-[#304638] dark:bg-[#1d2d23] dark:text-white" /><div className="grid gap-5 md:grid-cols-2"><select required name="category_id" value={form.category_id} onChange={change} className="rounded-xl border border-[#dce5dc] bg-white p-3 dark:border-[#304638] dark:bg-[#1d2d23] dark:text-white"><option value="">Select category</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select><select name="status" value={form.status} onChange={change} className="rounded-xl border border-[#dce5dc] bg-white p-3 dark:border-[#304638] dark:bg-[#1d2d23] dark:text-white"><option value="draft">Draft</option><option value="published">Published</option></select></div><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-blue-300 bg-blue-50 p-4 text-sm text-blue-700 dark:bg-[#172c3d]"><ImagePlus size={20} />{uploading ? 'Uploading…' : 'Upload cover image'}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload} className="hidden" /></label>{form.cover_image && <img src={form.cover_image.startsWith('http') ? form.cover_image : API + form.cover_image} alt="Cover preview" className="max-h-64 w-full rounded-xl object-cover" />}<textarea required minLength="20" name="content" value={form.content} onChange={change} rows="18" placeholder={'Write in Markdown…\n\n## A heading\n\n```java\nSystem.out.println("Hello");\n```'} className="w-full rounded-2xl border border-[#dce5dc] bg-white p-4 font-mono text-sm leading-7 outline-none focus:border-blue-400 dark:border-[#304638] dark:bg-[#1d2d23] dark:text-white" />{error && <p className="text-red-500">{error}</p>}<button disabled={busy || uploading} className="flex items-center gap-2 rounded-xl bg-blue-500 px-5 py-3 font-semibold text-white hover:bg-blue-400 disabled:opacity-60"><Save size={17} />{busy ? 'Saving…' : 'Save story'}</button></form></main>;
}
