import { useEffect, useState } from 'react';
import { ArrowRight, Mail, Search, Sparkles } from 'lucide-react';
import { api } from '../services/api';
import PostCard from '../components/PostCard';
import Loading from '../components/Loading';

const projects = [
  ['Student Management System', 'Java · Spring Boot · MySQL', 'A practical full-stack study in CRUD workflows, validation, Thymeleaf, and REST APIs.'],
  ['Job Portal / Job Application System', 'Python · FastAPI · PDBC · MySQL · mysql.connector · venv', 'A menu-driven capstone built step by step: database design, parameterized SQL, jobs, candidates, applications, validation, testing, and documentation.'],
  ['Hand Gesture Recognition', 'Python · TensorFlow · OpenCV', 'A computer-vision experiment combining gestures and voice commands.'],
  ['Application Log Monitor', 'Bash · Unix/Linux · Shell', 'A support practice project for detecting errors, checking processes, and generating alerts.'],
  ['Weather Data Integration API', 'Apigee X · OpenWeatherMap · Swagger · Postman', 'An API management project exposing weather data through a governed proxy with validation, security, and traffic policies.'],
  ['Online Bookstore API Gateway', 'Apigee X · OAuth 2.0 · Swagger · Jenkins', 'A gateway concept routing Books, Users, and Orders services through authentication and API policies.'],
  ['Movie Info API Management', 'Apigee X · OMDb API · OAuth 2.0', 'A managed API project focused on authentication, response transformation, and consistent error handling.'],
];
const localNotes = [
  { id: 'local-1', slug: 'building-job-portal-python-mysql', title: 'Building a Job Portal with Python, PDBC, and FastAPI', excerpt: 'A staged MySQL and Python capstone using PDBC, FastAPI, mysql.connector, venv, jobs, candidates, applications, validation, testing, and documentation.', content: 'The Job Portal / Job Application System is built step by step with Python, PDBC principles, FastAPI, mysql.connector, and a Python virtual environment: requirements, MySQL tables, tested SQL, database.py, functions.py, a menu-driven main.py, validation, exception handling, testing, README documentation, resume bullets, and interview preparation.', category: { name: 'Python' }, author: { name: 'Akash Bondada' }, created_at: '2026-10-01T00:00:00Z' },
  { id: 'local-2', slug: 'building-apis-with-fastapi-and-pdbc', title: 'Building APIs with FastAPI and PDBC', excerpt: 'A practical note on FastAPI, PDBC principles, MySQL connectivity, validation, and clean Python project structure.', content: 'FastAPI, PDBC principles, mysql.connector, a Python virtual environment, validation, reusable functions, and the Job Portal learning plan.', category: { name: 'FastAPI' }, author: { name: 'Akash Bondada' }, created_at: '2026-06-01T00:00:00Z' },
  { id: 'local-4', slug: 'apigee-api-management-patterns', title: 'Apigee API Management Patterns', excerpt: 'Notes on API proxies, OAuth 2.0, JWT validation, quota, spike arrest, fault handling, and API lifecycle thinking.', content: 'Mentored Apigee/API Management exposure covering API proxy development, REST design, OAuth 2.0, JWT validation, API key verification, quota, spike arrest, policies, fault handling, Postman, and Swagger/OpenAPI.', category: { name: 'Apigee' }, author: { name: 'Akash Bondada' }, created_at: '2026-05-15T00:00:00Z' },
  { id: 'local-3', slug: 'application-log-monitor-linux', title: 'Application Log Monitoring with Bash and Linux', excerpt: 'A support practice workflow for detecting log errors, checking disk space, validating processes, and generating alerts.', content: 'A support practice workflow using Bash and Unix/Linux commands to inspect logs, validate processes, check disk space, and generate alerts.', category: { name: 'Application Support' }, author: { name: 'Akash Bondada' }, created_at: '2026-05-01T00:00:00Z' },
];

export default function Home() {
  const [posts, setPosts] = useState(null), [categories, setCategories] = useState([]), [search, setSearch] = useState(''), [category, setCategory] = useState(''), [page, setPage] = useState(1), [email, setEmail] = useState(''), [subscribed, setSubscribed] = useState(false);
  useEffect(() => { api.get('/categories').then(setCategories); }, []);
  useEffect(() => { api.get(`/posts?page=${page}&limit=6${search ? `&search=${encodeURIComponent(search)}` : ''}${category ? `&category=${category}` : ''}`).then(setPosts).catch(() => setPosts({ items: localNotes.filter((post) => !search || post.title.toLowerCase().includes(search.toLowerCase())).filter((post) => !category || post.category.name.toLowerCase().includes(category.toLowerCase())), pages: 1, offline: true })); }, [page, category, search]);
  const featured = posts?.items?.[0];
  const latest = posts?.items?.slice(1) || [];
  return <main>
    <section className="border-b border-[#dce5dc] bg-[#eef4ef] dark:bg-[#182a1d]"><div className="mx-auto max-w-6xl px-5 pb-20 pt-20 md:pb-28 md:pt-28"><div className="max-w-4xl"><div className="mb-6 flex items-center gap-2 text-sm font-semibold uppercase tracking-wider text-blue-600"><Sparkles size={16} /> Akash Bondada · Technical journal</div><h1 className="serif text-6xl leading-[.98] tracking-tight text-ink md:text-8xl dark:text-white">Ideas from the <em className="text-blue-600">stack.</em></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-gray-600 dark:text-gray-300">A reading-focused developer blog about Java, Spring Boot, Python, REST APIs, SQL, Apigee, Linux, and learning through real projects.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#journal" className="rounded-xl bg-blue-500 px-5 py-3 text-sm font-semibold text-white">Read the journal <ArrowRight className="ml-2 inline" size={16} /></a><a href="#about" className="rounded-xl border border-[#b9cfbf] px-5 py-3 text-sm font-semibold text-moss">About the author</a></div></div></div></section>
    {featured && <section className="mx-auto max-w-6xl px-5 py-16"><div className="mb-7 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-500">Featured reading</p><h2 className="serif mt-2 text-4xl dark:text-white">Start here.</h2></div><span className="hidden text-sm text-gray-500 md:block">A practical note from the journal</span></div><PostCard post={featured} index={0} featured /></section>}
    <section id="journal" className="border-y border-[#dce5dc] bg-white py-20 dark:bg-[#19271e]"><div className="mx-auto max-w-6xl px-5"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-500">The journal</p><h2 className="serif mt-2 text-5xl dark:text-white">Latest notes.</h2></div><div className="relative"><Search className="absolute left-3 top-3 text-gray-400" size={17} /><input aria-label="Search articles" placeholder="Search articles" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} className="w-56 rounded-xl border border-[#dce5dc] bg-cream py-2.5 pl-10 pr-4 text-sm outline-none focus:border-blue-400 dark:border-[#2d4667] dark:bg-[#1d2d23] dark:text-white" /></div></div><div className="mb-9 flex flex-wrap gap-2"><button onClick={() => { setCategory(''); setPage(1); }} className={`rounded-full px-4 py-2 text-sm ${!category ? 'bg-blue-500 text-white' : 'bg-sage text-moss'}`}>All topics</button>{categories.map((item) => <button key={item.id} onClick={() => { setCategory(String(item.id)); setPage(1); }} className={`rounded-full px-4 py-2 text-sm ${category === String(item.id) ? 'bg-blue-500 text-white' : 'bg-sage text-moss'}`}>{item.name}</button>)}</div>{posts === null ? <Loading /> : posts.items.length ? <><div className="grid gap-6 md:grid-cols-3">{latest.map((post, index) => <PostCard key={post.id} post={post} index={index + 1} />)}</div>{latest.length === 0 && <p className="rounded-2xl bg-sage p-8 text-center text-gray-500">This topic’s featured story is the first entry. More notes are coming soon.</p>}<div className="mt-10 flex items-center justify-center gap-4"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded-xl border border-[#dce5dc] px-4 py-2 text-sm disabled:opacity-40">Previous</button><span className="text-sm text-gray-500">Page {page} of {posts.pages}</span><button disabled={page >= posts.pages} onClick={() => setPage(page + 1)} className="rounded-xl bg-blue-500 px-4 py-2 text-sm text-white disabled:opacity-40">Next</button></div></> : <p className="rounded-2xl bg-sage p-8 text-center text-gray-500">No articles matched your search.</p>}</div></section>
    <section id="about" className="mx-auto grid max-w-6xl gap-12 px-5 py-20 md:grid-cols-[1fr_1.5fr] md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-500">About this journal</p><h2 className="serif mt-3 text-5xl dark:text-white">Written by a developer, while learning in public.</h2></div><div><p className="text-lg leading-8 text-gray-600 dark:text-gray-300">I’m <strong>Akash Bondada</strong>, an MCA graduate and Full Stack Developer candidate from Hyderabad. I write about the tools I practise: Java, Spring Boot, Python, REST APIs, SQL, Apigee/API Management, Unix/Linux, and application support.</p><p className="mt-5 leading-7 text-gray-500 dark:text-gray-400">These notes are grounded in training, projects, and mentored practical exposure—not abstract claims. My goal is to make each article useful to someone building or troubleshooting their next system.</p><div className="mt-6 flex flex-wrap gap-3 text-sm"><span className="rounded-full bg-sage px-4 py-2 text-moss">MCA · Andhra University</span><span className="rounded-full bg-sage px-4 py-2 text-moss">Hyderabad, India</span><a href="mailto:akashbondada4@gmail.com" className="rounded-full bg-sage px-4 py-2 text-moss">Contact Akash</a></div></div></section>
    <section id="work" className="bg-[#0d1728] py-20 text-white"><div className="mx-auto max-w-6xl px-5"><div className="mb-9"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-400">Context behind the writing</p><h2 className="serif mt-3 text-5xl">Projects I learn from.</h2><p className="mt-4 max-w-2xl text-gray-400">The journal is the focus. These projects are included as context for the lessons and experiments behind each article.</p></div><div className="grid gap-5 md:grid-cols-3">{projects.map(([title, tech, description]) => <article key={title} className="rounded-2xl border border-[#2d4667] bg-[#142137] p-6 transition hover:-translate-y-1 hover:border-blue-400"><p className="font-mono text-xs text-blue-400">CASE NOTE</p><h3 className="serif mt-8 text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-gray-400">{description}</p><p className="mt-5 text-xs font-semibold text-emerald-300">{tech}</p></article>)}</div></div></section>
    <section className="bg-[#eaf2ff] py-16 dark:bg-[#172c3d]"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-8 px-5 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-500">Stay in the loop</p><h2 className="serif mt-3 text-4xl dark:text-white">New notes, occasionally.</h2><p className="mt-3 text-gray-500 dark:text-gray-300">No noise—just practical developer writing.</p></div><form onSubmit={(event) => { event.preventDefault(); setSubscribed(true); setEmail(''); }} className="flex max-w-md flex-1 gap-2"><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Your email address" className="min-w-0 flex-1 rounded-xl border-0 px-4 py-3 outline-none" /><button className="rounded-xl bg-blue-500 px-5 py-3 text-sm font-semibold text-white">{subscribed ? 'Subscribed' : 'Subscribe'}</button></form></div></section>
    <section id="contact" className="bg-[#0d1728] py-20 text-center text-white"><Mail className="mx-auto mb-5 text-blue-400" /><h2 className="serif text-5xl">Have a topic in mind?</h2><p className="mx-auto mt-5 max-w-lg text-gray-400">Reach out about Java, APIs, SQL, support engineering, or a future article.</p><a href="mailto:akashbondada4@gmail.com" className="mt-8 inline-flex rounded-xl bg-blue-500 px-5 py-3 text-sm font-semibold">akashbondada4@gmail.com</a></section>
  </main>;
}
